name: factionlogo
main: net.nullcraft.factionlogo.FactionLogoPlugin
author: garypwn
version: ${version}
softdepend: [LegacyFactions, Factions, Kingdoms, PlaceholderAPI]
commands:
    setlogo:
        description: Set a faction logo.
        usage: /setlogo <TARGET> <LOGO>
    factionlogo:
        description: Reload configs
        usage: /factionlogo
permissions:
    factionlogo.any:
        description: Set any faction's logo.
        default: op